name: Docker Image CI

on:
  pull_request:
    paths:
      - Dockerfile
      - docker-compose.yml
      - '.github/workflows/docker-image.yml'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build -t portal-image .

      - name: Verify container
        run: docker run --rm portal-image php -v

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image on release
        if: github.event_name == 'release'
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          docker tag portal-image $IMAGE
          docker push $IMAGE
