name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release-**" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ce-portal-app
          tags: |
            type=ref,event=pr
            type=sha

      - name: Build (no push) with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
