name: Laravel Push Test

on: [push]

jobs:
    laravel-tests:
        runs-on: ubuntu-latest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

        steps:
            - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                  php-version: '8.0'
            - uses: actions/checkout@v2
            - name: Copy .env
              run: php -r "file_exists('.env') || copy('.env.example', '.env');"

            - name: Remove existing composer.lock
              run: rm ./composer.lock

            - name: Install Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Create Database
              run: |
                  mkdir -p database
                  touch database/database.sqlite

            - name: Generate key
              run: php artisan key:generate

            - name: Directory Permissions
              run: chmod -R 777 storage bootstrap/cache
                  
            - name: Execute tests (Unit and Feature tests) via PHPUnit
              run: |
                  php artisan test -p --colors --debug --coverage-clover=coverage.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
                